projects:
  simpson:
    schemaPath: src/api/graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/api/graphql
extensions:
  amplify:
    version: 3
