// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:de877bf1-912e-4846-9169-9b9fdfe32ca8",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_gVthOQsd9",
    "aws_user_pools_web_client_id": "6q96gvm241bfnfrdm4m2bjnhon",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://m473akiayzfstb2awt2wzp5bke.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
